<a href="https://colab.research.google.com/github/nguyenhaianh123-code/E-wallet/blob/main/e_wallet.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Given dataset

Suppose you are a DA in an e-wallet company, and you need to analyze the following datasets:  

- payment_report.csv (monthly payment volume of products).

- product.csv (product information).

- transactions.csv (transactions information)

Statement: Muốn hiểu về tình trạng payment hoặc transaction trong context của một ewallet.

#Import Data/Libraries

In [5]:
import numpy as np
import pandas as pd

In [4]:
product = pd.read_csv("/content/sample_data/product.csv")
payment_report = pd.read_csv("/content/sample_data/payment_report.csv")
transactions = pd.read_csv("/content/sample_data/transactions.csv")

In [ ]:
transactions.head()

,transaction_id,merchant_id,volume,transType,transStatus,sender_id,receiver_id,extra_info,timeStamp
0,3002692434,5,100000,24,1.0,10199794.0,199794.0,NaN,1.682932e+12
1,3002692437,305,20000,2,1.0,14022211.0,14022211.0,NaN,1.682932e+12
2,3001960110,7255,48605,22,1.0,NaN,10530940.0,NaN,1.682932e+12
3,3002680710,2270,1500000,2,1.0,10059206.0,59206.0,NaN,1.682932e+12
4,3002680713,2275,90000,2,1.0,10004711.0,4711.0,NaN,1.682932e+12

In [ ]:
payment_report.head()

  report_month payment_group  product_id  source_id     volume
0      2023-01       payment          12         45  624110375
1      2023-01       payment          17         45  335715113
2      2023-01       payment          18         45  737784466
3      2023-01       payment          19         45  120963069
4      2023-01       payment          20         45  319653158

In [ ]:
product.head()

   product_id category team_own
0          17  PXXXXXB      ASD
1          18  PXXXXXB      ASD
2          20  PXXXXXB      ASD
3         287  PXXXXXB      ASD
4         372  PXXXXXB      ASD

#Part 1: EDA

## EDA payment_report.csv & product.csv

Check each column: missing data? duplicates? incorrect data types?
Summarize numerical data: any incorrect values?


1.   List item
2.   List item

In [6]:
payment_enriched = payment_report.merge(product, how='left', on='product_id')
payment_enriched

,report_month,payment_group,product_id,source_id,volume,category,team_own
0,2023-01,payment,12,45,624110375,PXXXXXT,ASD
1,2023-01,payment,17,45,335715113,PXXXXXB,ASD
2,2023-01,payment,18,45,737784466,PXXXXXB,ASD
3,2023-01,payment,19,45,120963069,PXXXXXM2,ASD
4,2023-01,payment,20,45,319653158,PXXXXXB,ASD
...,...,...,...,...,...,...,...
914,2023-04,payment,15067,45,1504000,PXXXXXR,ASL
915,2023-04,refund,1976,37,3542271587,NaN,NaN
916,2023-04,refund,1976,38,13831708189,NaN,NaN
917,2023-04,refund,1976,39,1905435543,NaN,NaN
918,2023-04,refund,1976,39,3679922071,NaN,NaN

###Check data type của tất cả các cột

In [7]:
data_types = payment_enriched.dtypes
print(data_types)

report_month     object
payment_group    object
product_id        int64
source_id         int64
volume            int64
category         object
team_own         object
dtype: object

In [ ]:
d_types = payment_enriched.describe()
print(data_types)

report_month     object
payment_group    object
product_id        int64
source_id         int64
volume            int64
category         object
team_own         object
dtype: object

###Check missing value của tất cả các cột

In [ ]:
missing_data = payment_enriched.isnull().sum()
print("Missing Data:\n", missing_data)

Missing Data:
 report_month      0
payment_group     0
product_id        0
source_id         0
volume            0
category         22
team_own         22
dtype: int64

###Check duplicate

In [8]:
duplicate_data = payment_enriched.duplicated().sum()
print(f"Number of duplicate rows: {duplicate_data}")

Number of duplicate rows: 0

##EDA transaction.csv

###Check missing value

In [9]:
missing_data_transact = transactions.isnull().sum()
print("Missing Data:\n", missing_data_transact)

Missing Data:
 transaction_id         0
merchant_id            0
volume                 0
transType              0
transStatus            0
sender_id          28205
receiver_id        94308
extra_info        759601
timeStamp              0
dtype: int64

###Check data type

In [10]:
d_types_transact = transactions.dtypes
print(d_types_transact)

transaction_id      int64
merchant_id         int64
volume              int64
transType           int64
transStatus         int64
sender_id         float64
receiver_id       float64
extra_info         object
timeStamp           int64
dtype: object

--> datatype timestamp đang sai --> chuyển thành

###Check duplicate

In [ ]:
duplicate_data_transact = transactions.duplicated().sum()
print(f"Number of duplicate rows: {duplicate_data_transact}")

Number of duplicate rows: 28

In [12]:
transactions = transactions.drop_duplicates()

Đổi data type của timeStamp về dạng date time

In [18]:
transactions['timeStamp'] = pd.to_datetime(transactions['timeStamp']).dt.date
transactions

,transaction_id,merchant_id,volume,transType,transStatus,sender_id,receiver_id,extra_info,timeStamp
0,3002692434,5,100000,24,1,10199794.0,199794.0,NaN,2023-05-01
1,3002692437,305,20000,2,1,14022211.0,14022211.0,NaN,2023-05-01
2,3001960110,7255,48605,22,1,NaN,10530940.0,NaN,2023-05-01
3,3002680710,2270,1500000,2,1,10059206.0,59206.0,NaN,2023-05-01
4,3002680713,2275,90000,2,1,10004711.0,4711.0,NaN,2023-05-01
...,...,...,...,...,...,...,...,...,...
763025,3003518391,2895,22000,2,1,10031248.0,NaN,NaN,2023-05-03
763026,3003507360,2270,50000,2,1,21015351.0,21015351.0,NaN,2023-05-03
763027,3003528984,2270,10000,2,1,31552906.0,31552906.0,NaN,2023-05-03
763028,3003507363,305,20000,2,1,10156023.0,156023.0,NaN,2023-05-03
763029,3003518394,5390,25000,2,1,10003668.0,NaN,NaN,1970-01-01

Check tranStatus gồm những giá trị nào

In [19]:
unique_values = transactions['transStatus'].unique()
print(unique_values)

[    1  -217   -68  -358  -357  -344  -332  -200  -351   -54  -333   -63
  -348 -1333  -354  -131  -994  -352  -998  -356  -239  -309  -361   -92
  -359  -129  -308  -244  -161  -340  -355   -87]

#Part II: Data Wrangling

##1. Top 3 product_ids with the highest volume.

In [20]:
top_3_products = payment_enriched.groupby('product_id')['volume'].sum().nlargest(3)
print(top_3_products)

product_id
1976    61797583647
429     14667676567
372     13713658515
Name: volume, dtype: int64

##2. Given that 1 product_id is only owed by 1 team, are there any abnormal products against this rule?

In [25]:
# Nhóm theo 'product_id' và đếm số lượng đội duy nhất ('nunique') trong cột 'team_own'
violation_products = payment_enriched.groupby('product_id')['team_own'].nunique()
print(violation_products)

product_id
3        0
12       1
15       1
17       1
18       1
        ..
2419     1
2587     1
10033    0
10039    1
15067    1
Name: team_own, Length: 311, dtype: int64

In [24]:
# Lọc ra các sản phẩm có số đội sở hữu > 1 (vi phạm quy tắc)
abnormal_products = violation_products[violation_products > 1]
print(abnormal_products)

Series([], Name: team_own, dtype: int64)

--> không có sản phẩm nào vi phạm quy tắc

##3. Find the team has had the lowest performance (lowest volume) since Q2.2023. Find the category that contributes the least to that team.

In [27]:
# Lọc dữ liệu từ Q2.2023 trở đi
filtered_data = payment_enriched[payment_enriched['report_month'] >= '2023-04']
print(filtered_data)

    report_month payment_group  product_id  source_id       volume category  \
638      2023-04       payment           3         45         6000      NaN
639      2023-04       payment          12         45    379013493  PXXXXXT
640      2023-04       payment          15         45   2810487679  PXXXXXG
641      2023-04       payment          17         45    489440838  PXXXXXB
642      2023-04       payment          18         45   1261017518  PXXXXXB
..           ...           ...         ...        ...          ...      ...
914      2023-04       payment       15067         45      1504000  PXXXXXR
915      2023-04        refund        1976         37   3542271587      NaN
916      2023-04        refund        1976         38  13831708189      NaN
917      2023-04        refund        1976         39   1905435543      NaN
918      2023-04        refund        1976         39   3679922071      NaN

    team_own
638      NaN
639      ASD
640      ASD
641      ASD
642      ASD
..       ...
914      ASL
915      NaN
916      NaN
917      NaN
918      NaN

[281 rows x 7 columns]

In [39]:
# Tính tổng volume theo đội (team_own)
team_performance = filtered_data.groupby('team_own')['volume'].sum()

# Sắp xếp theo volume tăng dần
team_performance_sort = team_performance.sort_values(ascending=True)
lowest_perform_team = team_performance_sort.idxmin()  # Lấy tên đội
lowest_perform_volume = team_performance_sort.iloc[0]  # Lấy volume của đội


print(f"Team with the lowest performance: {lowest_perform_team} with volume: {lowest_perform_volume}")

Team with the lowest performance: APS with volume: 51141753

In [41]:
# Lọc dữ liệu bảng filtered_data chỉ bao gồm đội có hiệu suất thấp nhất
team_data = filtered_data[filtered_data['team_own'] == lowest_perform_team]

# Tính tổng volume theo category
category_performance = team_data.groupby('category')['volume'].sum()

# Tìm category có hiệu suất thấp nhất
lowest_contrib_category = category_performance.idxmin()
print(f"Category with lowest contribution to the team: {lowest_contrib_category}")

Category with lowest contribution to the team: PXXXXXE

##4. Find the contribution of source_ids of refund transactions (payment_group = ‘refund’), what is the source_id with the highest contribution?

In [44]:
# Lọc payment_group='refund'
refund_transactions = payment_enriched[payment_enriched['payment_group'] == 'refund']
print(refund_transactions)

    report_month payment_group  product_id  source_id       volume category  \
192      2023-01        refund        1976         37    852173308      NaN
193      2023-01        refund        1976         38   3520890417      NaN
194      2023-01        refund        1976         39    443387276      NaN
195      2023-01        refund        1976         39    111281678      NaN
409      2023-02        refund        1976         39       111500      NaN
410      2023-02        refund        1976         37   1794436949      NaN
411      2023-02        refund        1976         38   7522440976      NaN
412      2023-02        refund        1976         39    910819764      NaN
413      2023-02        refund        1976         39   2675894726      NaN
634      2023-03        refund        1976         37   2962187382      NaN
635      2023-03        refund        1976         38  11652415177      NaN
636      2023-03        refund        1976         39   1660931261      NaN
637      2023-03        refund        1976         39   4731275843      NaN
915      2023-04        refund        1976         37   3542271587      NaN
916      2023-04        refund        1976         38  13831708189      NaN
917      2023-04        refund        1976         39   1905435543      NaN
918      2023-04        refund        1976         39   3679922071      NaN

    team_own
192      NaN
193      NaN
194      NaN
195      NaN
409      NaN
410      NaN
411      NaN
412      NaN
413      NaN
634      NaN
635      NaN
636      NaN
637      NaN
915      NaN
916      NaN
917      NaN
918      NaN

In [46]:
#Tính tổng volumn theo source_id
volumn_by_id = refund_transactions.groupby('source_id')['volume'].sum()
print(volumn_by_id)

#id with highest contribution
highest_contribution_id = volumn_by_id.idxmax()
print(f"Source_id with highest contribution: {highest_contribution_id}")

source_id
37     9151069226
38    36527454759
39    16119059662
Name: volume, dtype: int64
Source_id with highest contribution: 38

##5. Define type of transactions (‘transaction_type’) for each row, given:
- transType = 2 & merchant_id = 1205: Bank Transfer Transaction
- transType = 2 & merchant_id = 2260: Withdraw Money Transaction
- transType = 2 & merchant_id = 2270: Top Up Money Transaction
- transType = 2 & others merchant_id: Payment Transaction
- transType = 8, merchant_id = 2250: Transfer Money Transaction
- transType = 8 & others merchant_id: Split Bill Transaction
- Remained cases are invalid transactions

In [48]:
# prompt: Define type of transactions (‘transaction_type’) for each row, given:
# - transType = 2 & merchant_id = 1205: Bank Transfer Transaction
# - transType = 2 & merchant_id = 2260: Withdraw Money Transaction
# - transType = 2 & merchant_id = 2270: Top Up Money Transaction
# - transType = 2 & others merchant_id: Payment Transaction
# - transType = 8, merchant_id = 2250: Transfer Money Transaction
# - transType = 8 & others merchant_id: Split Bill Transaction
# - Remained cases are invalid transactions

def categorize_transaction(row):
    if row['transType'] == 2:
        if row['merchant_id'] == 1205:
            return 'Bank Transfer Transaction'
        elif row['merchant_id'] == 2260:
            return 'Withdraw Money Transaction'
        elif row['merchant_id'] == 2270:
            return 'Top Up Money Transaction'
        else:
            return 'Payment Transaction'
    elif row['transType'] == 8:
        if row['merchant_id'] == 2250:
            return 'Transfer Money Transaction'
        else:
            return 'Split Bill Transaction'
    else:
        return 'Invalid Transaction'

transactions['transaction_type'] = transactions.apply(categorize_transaction, axis=1)
transactions

,transaction_id,merchant_id,volume,transType,transStatus,sender_id,receiver_id,extra_info,timeStamp,transaction_type
0,3002692434,5,100000,24,1,10199794.0,199794.0,NaN,2023-05-01,Invalid Transaction
1,3002692437,305,20000,2,1,14022211.0,14022211.0,NaN,2023-05-01,Payment Transaction
2,3001960110,7255,48605,22,1,NaN,10530940.0,NaN,2023-05-01,Invalid Transaction
3,3002680710,2270,1500000,2,1,10059206.0,59206.0,NaN,2023-05-01,Top Up Money Transaction
4,3002680713,2275,90000,2,1,10004711.0,4711.0,NaN,2023-05-01,Payment Transaction
...,...,...,...,...,...,...,...,...,...,...
763025,3003518391,2895,22000,2,1,10031248.0,NaN,NaN,2023-05-03,Payment Transaction
763026,3003507360,2270,50000,2,1,21015351.0,21015351.0,NaN,2023-05-03,Top Up Money Transaction
763027,3003528984,2270,10000,2,1,31552906.0,31552906.0,NaN,2023-05-03,Top Up Money Transaction
763028,3003507363,305,20000,2,1,10156023.0,156023.0,NaN,2023-05-03,Payment Transaction
763029,3003518394,5390,25000,2,1,10003668.0,NaN,NaN,1970-01-01,Payment Transaction

##6. Of each transaction type (excluding invalid transactions): find the number of transactions, volume, senders and receivers.

In [51]:
# Lọc các giao dịch không phải Invalid Transaction
valid_transactions = transactions[transactions['transaction_type'] != 'Invalid Transaction']

# Nhóm theo transaction_type và tính toán các giá trị cần thiết
transaction_summary = valid_transactions.groupby('transaction_type').agg(
    num_transactions=('transaction_type', 'count'),  # Số lượng giao dịch
    total_volume=('volume', 'sum'),  # Tổng volume
    num_senders=('sender_id', 'nunique'),  # Số lượng senders duy nhất
    num_receivers=('receiver_id', 'nunique')  # Số lượng receivers duy nhất
)

print(transaction_summary)

                            num_transactions  total_volume  num_senders  \
transaction_type
Bank Transfer Transaction              21903   29460804712        15252
Payment Transaction                   229141   40896483666       103857
Split Bill Transaction                   788       3047729          765
Top Up Money Transaction              167623   62117245576        80791
Transfer Money Transaction            197216   21574259700        28944
Withdraw Money Transaction             19241   13173562449        15708

                            num_receivers
transaction_type
Bank Transfer Transaction            6051
Payment Transaction                 81633
Split Bill Transaction                366
Top Up Money Transaction            80791
Transfer Money Transaction          23976
Withdraw Money Transaction          15708